### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by gure59753212** [gure59753212/furima-36573#22]
# フリマアプリのURL
https://furima-36573.herokuapp.com/

# Basic認証のIDとパスワード
ID：user
パスワード：8925

# 出品者用のメールアドレスとパスワード
メールアドレス：test1@mail.com
パスワード：a12345

# 購入者用のメールアドレスとパスワード
メールアドレス：test2@mail.com
パスワード：a12345

**Comment by takumi0530** [comment]
@gure59753212 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [ ] **必要な情報を適切に入力して「購入」ボタンを押すと、商品の購入ができること**
情報を全て埋め、購入ボタンを押すとエラーページに遷移してしまいます。
**※上記により、購入機能・売却後の商品の動作確認ができておりません。次回ご提出時に確認させていただきます。**
<img width="585" alt="スクリーンショット 2021-09-22 12 16 49" src="https://user-images.githubusercontent.com/76197191/134278273-18c78361-26e6-49f3-93f2-d253423405a1.png">

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A
